name: Sync Dependency Database

on:
  schedule:
    # Runs every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create dep-files directory if missing
        run: mkdir -p dep-files

      - name: Download and sync files
        run: |
          wget --recursive \
               --no-parent \
               --no-host-directories \
               --cut-dirs=4 \
               --reject "index.html*" \
               --reject "robots.txt*" \
               --directory-prefix=dep-files \
               --no-verbose \
               https://slackware.uk/slackel/x86_64/slackware-current/deps/

            last_dir=$(pwd)
            
            cd dep-files

            ls | xargs -i  md5sum {} | awk '{ print $2"|"$1 }' > dep-file-checksums.txt
            md5sum dep-file-checksums.txt | awk '{ print $1 }' > dep-file-checksums.md5
               
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: weekly sync of dependency database files'
          file_pattern: |
                         dep-files/*
                         dep-file-checksums.txt
                         dep-file-checksums.md5                         
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
